cart/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/(?P<size>[-\w ]+)/$', views.cart_remove, name='cart_remove')
]

gorgeous/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^contact/', views.contact, name='contact'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponse, JsonResponse

from products.models import Product
from .cart import Cart
from .forms import CartForm

# views created following instructions by Antonio Mele
# in the book Django By Example
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    # get product object by id
    product = get_object_or_404(Product, id=product_id)
    # get selected size from request data
    size = request.POST['size']
    form = CartForm(request.POST)

    if form.is_valid():
        # add product to the cart
        # or update it's quantity/ size
        updated_cart = cart.add(product=product, size=size, quantity=form.cleaned_data['quantity'],
                                update=form.cleaned_data['update'])
        if updated_cart:
            # if cart updated return success status
            subtotal_price = cart.get_subtotal_price()
            delivery_price = cart.get_delivery_price()
            total_price = cart.get_total_price()
            data = {
                'subtotal_price': subtotal_price,
                'delivery_price': delivery_price,
                'total_price': total_price
            }
            return JsonResponse(data, status=200)
        else:
            # if cart not updated return error message
            return HttpResponse(status=400)

def cart_remove(request, product_id, size):
    cart = Cart(request)
    cart.remove(product_id, size)
    return redirect('cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        # create form for each item in the cart
        # to allow updating its quantity and size
        item['update_quantity_form'] = CartForm(initial={'quantity': item['quantity'],'update': True})
    args = {'cart': cart}
    return render(request, 'cart/cart.html', args)

templates/cart/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
           <div class="col">
                <h1 class="heading heading--top">Shopping bag</h1>
            </div>
        </div>
        <div class="row">
           <div class="cart col-12 col-lg-10 col-xl-8">
                {% if cart %}
                <div class="row">
                    <div class="cart-products col-12 col-md-7">
                        <div class="cart-container cart-container--products">
                            {% for item in cart %}
                                <div class="product-item">
                                    {% with product=item.product %}
                                        <img class="product-item__img" src="{{ item.image.image.url }}" alt="">
                                        <div class="product-item__details">
                                            <p>{{ product.name }}</p>
                                            <p class="product-item__price">£{{ item.price }}</p>
                                            <form class="product-item__form" action="{% url 'cart_add' product.id %}" method="post">
                                                {% csrf_token %}
                                                <div class="product-item__form-select">
                                                    <label for="size-update">Size:</label>
                                                    <select name="size" id="size-update" required>
                                                        {% for size in item.all_sizes %}
                                                            <option value="{{ size.size }}"{% if size not in item.sizes_available and size.size != item.size %}disabled{% endif %} {% if size.size == item.size %}selected{% endif %}>
                                                                {{ size.size }}{% if size not in item.sizes_available and size.size != item.size %} - Out of stock{% endif %}
                                                            </option>
                                                        {% endfor %}
                                                    </select>
                                                    <label for="id_quantity">Quantity:</label>
                                                    {{ item.update_quantity_form.quantity }}
                                                    {{ item.update_quantity_form.update }}
                                                </div>
                                                <div class="product-item__buttons">
                                                    <button class="button product-item__button product-item__button--update" type="submit">Update</button>
                                                    <p class="product-item__button product-item__button--cancel">Cancel</p>
                                                </div>
                                                <p class="cart-error-message">Quantity is not available</p>
                                            </form>
                                        </div>
                                        <a href="{% url "cart_remove" product.id item.size %}" class="cart-remove"><i class="fa fa-close" aria-hidden="true"></i></a>
                                    {% endwith %}
                                </div>
                            {% endfor %}
                            <p class="cart-subtotal"><span>Subtotal</span> <span class="price--subtotal">£{{ cart.get_subtotal_price }}</span></p>
                        </div>
                    </div>
                    <div class="col-12 col-md-5">
                        <div class="cart-container cart-container--total">
                            <div class="cart-prices">
                                <p><span>Subtotal</span> <span class="price price--subtotal">£{{ cart.get_subtotal_price }}</span></p>
                                <p><span>Delivery</span> <span class="price price--delivery">£{{ cart.get_delivery_price }}</span></p>
                            </div>
                            <div class="cart-total">
                                <p><span>Total</span> <span class="price price--total">£{{ cart.get_total_price }}</span></p>
                            </div>
                            <a href="{% url 'checkout' %}" class="button button--checkout">Checkout</a>
                        </div>
                    </div>
                </div>
                {% else %}
                    <div class="cart-empty">
                        <p>Your shopping bag is empty.</p>
                        <a href="{% url 'products_list' %}" class="button">Shop now</a>
                    </div>
                {% endif %}
           </div>
        </div>
    </div>
{% endblock %}